name: AnimalFarm
version: 1.0.0
author: dagxam
main: ru.dagxam.animalfarm.AnimalFarmPlugin
api-version: '26.2'
description: Расширенная система животноводства, кормушек, владельцев и аквакультуры.
website: https://github.com/dagxam/AnimalFarm

commands:
  animalfarm:
    description: Управление плагином AnimalFarm.
    usage: /animalfarm <trust|untrust|members|owner|transfer|reload|info>

permissions:
  animalfarm.admin:
    description: Полный административный доступ к AnimalFarm.
    default: op
