package ru.dagxam.animalfarm;

import org.bukkit.Location; import org.bukkit.Material; import org.bukkit.World; import org.bukkit.block.Barrel; import org.bukkit.entity.Animals; import org.bukkit.entity.Entity; import org.bukkit.entity.EntityType; import org.bukkit.entity.Fish; import org.bukkit.inventory.Inventory; import org.bukkit.inventory.ItemStack; import org.bukkit.persistence.PersistentDataType;
import java.util.*; import java.util.concurrent.ThreadLocalRandom;

/** Единый процессор фермы v2. Поддерживает вместимость, состояние, производство, пол животных и аквакультуру. */
public final class FarmProcessor {
    private final AnimalFarmPlugin plugin; private final FarmSettings settings; private final org.bukkit.NamespacedKey nextBreedDayKey,productionDayKey,goldenDayKey,goldenCyclesKey,farmStateKey;
    public FarmProcessor(AnimalFarmPlugin p,FarmSettings s){plugin=p;settings=s;nextBreedDayKey=new org.bukkit.NamespacedKey(p,"next_breed_day");productionDayKey=new org.bukkit.NamespacedKey(p,"production_day");goldenDayKey=new org.bukkit.NamespacedKey(p,"golden_day");goldenCyclesKey=new org.bukkit.NamespacedKey(p,"golden_cycles");farmStateKey=new org.bukkit.NamespacedKey(p,"farm_state");}
    public void process(FarmObjectKey key,FarmObjectType type,long tick){Location l=key.location(plugin.getServer());if(l.getWorld()==null||!(l.getBlock().getState() instanceof Barrel b))return;long day=l.getWorld().getFullTime()/24000L;if(type==FarmObjectType.LAND_FEEDER)processLand(b,l,day);else if(settings.aquariumEnabled())processAquarium(b,l,day);b.update(true,false);}
    private void processLand(Barrel f,Location l,long day){List<Animals>a=findNearbyAnimals(l);for(Animals x:a)plugin.genderManager().assignRandomIfSupported(x);updateLandState(f,a);long next=f.getPersistentDataContainer().getOrDefault(nextBreedDayKey,PersistentDataType.LONG,-1L);if(next<0||day>=next)runBreeding(f,a,day);long pd=f.getPersistentDataContainer().getOrDefault(productionDayKey,PersistentDataType.LONG,-1L);if(pd<day)runProduction(f,a,day);}
    private void updateLandState(Barrel f,List<Animals>a){Inventory i=f.getInventory();String s=a.size()>=settings.animalCapacity()?"FULL":(countAnimalFood(i)<settings.animalFoodMin()?"NO_FOOD":(count(i,Material.WATER_BUCKET)==0?"NO_WATER":"HEALTHY"));f.getPersistentDataContainer().set(farmStateKey,PersistentDataType.STRING,s);}
    private void runBreeding(Barrel f,List<Animals>a,long day){if(a.size()>=settings.animalCapacity())return;Inventory inv=f.getInventory();int cycles=goldenCycles(f,inv,day),bred=0;Map<EntityType,List<Animals>>g=new HashMap<>();for(Animals x:a)if(x.isAdult()&&x.canBreed()&&!x.isLoveMode())g.computeIfAbsent(x.getType(),k->new ArrayList<>()).add(x);outer:for(int c=0;c<cycles;c++)for(List<Animals> group:g.values()){Animals male=null,female=null;for(Animals x:group){if(plugin.genderManager().getOrAssign(x)==AnimalGender.MALE&&male==null)male=x;else if(plugin.genderManager().getOrAssign(x)==AnimalGender.FEMALE&&female==null)female=x;}if(male==null||female==null||!plugin.genderManager().canBreed(male,female))continue;if(bred>=settings.maxBreedingPairsPerDay()||a.size()+bred>=settings.animalCapacity())break outer;int cost=random(settings.animalFoodMin(),settings.animalFoodMax());if(!consumeFoodForPair(male,female,inv,cost)||!consumeWater(inv,1))continue;male.setLoveModeTicks(600);female.setLoveModeTicks(600);bred++;}f.getPersistentDataContainer().set(nextBreedDayKey,PersistentDataType.LONG,day+(cycles>1?1:random(1,3)));}
    private void runProduction(Barrel f,List<Animals>a,long day){Inventory inv=f.getInventory();int cycles=goldenCycles(f,inv,day),ch=0,sh=0,milk=0;for(Animals x:a)if(x.isAdult())switch(x.getType()){case CHICKEN->ch++;case SHEEP->sh++;case COW,GOAT->{if(plugin.genderManager().canGiveMilk(x))milk++;}default->{}}for(int c=0;c<cycles;c++){if(ch>0){int amount=Math.min(ch,random(plugin.getConfig().getInt("production.chicken.eggs-min",5),plugin.getConfig().getInt("production.chicken.eggs-max",10)));if(consumeAnyAnimalFood(inv,settings.animalFoodMin()))addItems(inv,Material.EGG,amount);}if(sh>0){int amount=Math.min(sh,random(plugin.getConfig().getInt("production.wool.min",2),plugin.getConfig().getInt("production.wool.max",3)));if(consumeAnyAnimalFood(inv,settings.animalFoodMin()))addItems(inv,Material.WHITE_WOOL,amount);}if(milk>0&&plugin.getConfig().getBoolean("milking.enabled",true)){int amount=Math.min(Math.min(milk,count(inv,Material.BUCKET)),random(plugin.getConfig().getInt("milking.milk-min",1),plugin.getConfig().getInt("milking.milk-max",3)));if(amount>0){remove(inv,Material.BUCKET,amount);addItems(inv,Material.MILK_BUCKET,amount);}}}f.getPersistentDataContainer().set(productionDayKey,PersistentDataType.LONG,day);}
    private int goldenCycles(Barrel f,Inventory inv,long day){long marked=f.getPersistentDataContainer().getOrDefault(goldenDayKey,PersistentDataType.LONG,-1L);if(marked==day)return f.getPersistentDataContainer().getOrDefault(goldenCyclesKey,PersistentDataType.INTEGER,1);int cycles=1;if(removeOneIfPresent(inv,Material.GOLDEN_APPLE)||removeOneIfPresent(inv,Material.GOLDEN_CARROT))cycles=random(settings.goldenCyclesMin(),settings.goldenCyclesMax());f.getPersistentDataContainer().set(goldenDayKey,PersistentDataType.LONG,day);f.getPersistentDataContainer().set(goldenCyclesKey,PersistentDataType.INTEGER,cycles);return cycles;}
    private void processAquarium(Barrel s,Location l,long day){List<Fish>fish=findNearbyFish(l);Inventory inv=s.getInventory();String state=fish.size()>=settings.fishCapacity()?"FULL":(countFishFood(inv)<settings.animalFoodMin()?"NO_FOOD":"HEALTHY");s.getPersistentDataContainer().set(farmStateKey,PersistentDataType.STRING,state);long next=s.getPersistentDataContainer().getOrDefault(nextBreedDayKey,PersistentDataType.LONG,-1L);if(next>=0&&day<next||fish.size()>=settings.fishCapacity())return;int cycles=goldenCycles(s,inv,day),created=0;Map<EntityType,List<Fish>>g=new HashMap<>();for(Fish x:fish)g.computeIfAbsent(x.getType(),k->new ArrayList<>()).add(x);outer:for(int c=0;c<cycles;c++)for(List<Fish>group:g.values())for(int n=0;n+1<group.size();n+=2){if(fish.size()+created>=settings.fishCapacity()||created>=settings.maxBreedingPairsPerDay())break outer;if(!consumeFishFood(inv,random(settings.animalFoodMin(),settings.animalFoodMax())))continue;Location w=findWater(l);if(w==null)break outer;l.getWorld().spawnEntity(w,group.get(n).getType());created++;}s.getPersistentDataContainer().set(nextBreedDayKey,PersistentDataType.LONG,day+(cycles>1?1:random(1,3)));}
    private List<Animals>findNearbyAnimals(Location l){List<Animals>o=new ArrayList<>();for(Entity e:l.getWorld().getNearbyEntities(l,settings.penMaxRadius()+1,settings.penVerticalRange(),settings.penMaxRadius()+1))if(e instanceof Animals a&&supported(a))o.add(a);return o;}
    private List<Fish>findNearbyFish(Location l){List<Fish>o=new ArrayList<>();for(Entity e:l.getWorld().getNearbyEntities(l,settings.aquariumMaxRadius(),settings.aquariumVerticalRange(),settings.aquariumMaxRadius()))if(e instanceof Fish f&&f.getLocation().getBlock().getType()==Material.WATER)o.add(f);return o;}
    private boolean supported(Animals a){return switch(a.getType()){case COW,SHEEP,GOAT,PIG,CHICKEN,HORSE,RABBIT->true;default->false;};}
    private Location findWater(Location c){World w=c.getWorld();if(w==null)return null;int r=settings.aquariumMaxRadius();for(int x=c.getBlockX()-r;x<=c.getBlockX()+r;x++)for(int y=c.getBlockY()-settings.aquariumVerticalRange();y<=c.getBlockY()+settings.aquariumVerticalRange();y++)for(int z=c.getBlockZ()-r;z<=c.getBlockZ()+r;z++)if(w.getBlockAt(x,y,z).getType()==Material.WATER)return new Location(w,x+.5,y+.2,z+.5);return null;}
    private boolean consumeFoodForPair(Animals a,Animals b,Inventory inv,int amount){Material fa=findFood(a,inv),fb=findFood(b,inv);if(fa==null||fb==null)return false;if(fa==fb&&count(inv,fa)<amount*2)return false;if(fa!=fb&&(count(inv,fa)<amount||count(inv,fb)<amount))return false;remove(inv,fa,amount);remove(inv,fb,amount);return true;}
    private Material findFood(Animals a,Inventory inv){for(String v:plugin.getConfig().getStringList("feeding."+a.getType().name().toLowerCase(Locale.ROOT)+".foods")){if("ANY_SEEDS".equalsIgnoreCase(v)){for(ItemStack i:inv.getContents())if(i!=null&&isSeed(i.getType()))return i.getType();}else{Material m=Material.matchMaterial(v);if(m!=null&&count(inv,m)>0)return m;}}return null;}
    private boolean consumeAnyAnimalFood(Inventory inv,int amount){for(int s=0;s<inv.getSize();s++){ItemStack i=inv.getItem(s);if(i!=null&&isAnimalFood(i.getType())&&i.getAmount()>=amount){i.setAmount(i.getAmount()-amount);if(i.getAmount()==0)inv.setItem(s,null);return true;}}return false;}
    private boolean consumeFishFood(Inventory inv,int amount){if(countFishFood(inv)<amount)return false;for(int s=0;s<inv.getSize()&&amount>0;s++){ItemStack i=inv.getItem(s);if(i==null||!isFishFood(i.getType()))continue;int t=Math.min(amount,i.getAmount());i.setAmount(i.getAmount()-t);if(i.getAmount()==0)inv.setItem(s,null);amount-=t;}return true;}
    private boolean consumeWater(Inventory inv,int amount){if(count(inv,Material.WATER_BUCKET)<amount)return false;remove(inv,Material.WATER_BUCKET,amount);addItems(inv,Material.BUCKET,amount);return true;}
    private int countAnimalFood(Inventory inv){int n=0;for(ItemStack i:inv.getContents())if(i!=null&&isAnimalFood(i.getType()))n+=i.getAmount();return n;} private int countFishFood(Inventory inv){int n=0;for(ItemStack i:inv.getContents())if(i!=null&&isFishFood(i.getType()))n+=i.getAmount();return n;}
    private boolean isSeed(Material m){return m.name().endsWith("_SEEDS")||m==Material.PITCHER_POD;} private boolean isFishFood(Material m){return isSeed(m)||m==Material.SEAGRASS||m==Material.KELP||m==Material.SEA_PICKLE;} private boolean isAnimalFood(Material m){return isFishFood(m)||m==Material.WHEAT||m==Material.HAY_BLOCK||m==Material.APPLE||m==Material.CARROT||m==Material.MELON_SLICE||m==Material.PUMPKIN||m==Material.MELON||m==Material.GOLDEN_APPLE||m==Material.GOLDEN_CARROT;}
    private int random(int min,int max){return ThreadLocalRandom.current().nextInt(Math.min(min,max),Math.max(min,max)+1);} private int count(Inventory inv,Material m){int n=0;for(ItemStack i:inv.getContents())if(i!=null&&i.getType()==m)n+=i.getAmount();return n;} private void remove(Inventory inv,Material m,int amount){for(int s=0;s<inv.getSize()&&amount>0;s++){ItemStack i=inv.getItem(s);if(i==null||i.getType()!=m)continue;int t=Math.min(amount,i.getAmount());i.setAmount(i.getAmount()-t);if(i.getAmount()==0)inv.setItem(s,null);amount-=t;}} private boolean removeOneIfPresent(Inventory inv,Material m){if(count(inv,m)==0)return false;remove(inv,m,1);return true;} private void addItems(Inventory inv,Material m,int amount){if(amount>0)inv.addItem(new ItemStack(m,amount));}
}
