package ru.dagxam.animalfarm;

import org.bukkit.*;
import org.bukkit.attribute.Attribute;
import org.bukkit.entity.*;
import org.bukkit.event.*;
import org.bukkit.event.block.Action;
import org.bukkit.event.player.*;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.*;
import java.io.*;
import java.util.*;

public final class MobBucketManager implements Listener {
 private final AnimalFarmPlugin plugin; private final NamespacedKey bucketKey,dataKey;
 public MobBucketManager(AnimalFarmPlugin p){plugin=p;bucketKey=new NamespacedKey(p,"mob_bucket");dataKey=new NamespacedKey(p,"mob_bucket_data");}
 @EventHandler(ignoreCancelled=true) public void capture(PlayerInteractEntityEvent e){if(e.getHand()!=EquipmentSlot.HAND||e.getRightClicked() instanceof Player||!(e.getRightClicked() instanceof LivingEntity mob)||!empty(e.getPlayer().getInventory().getItemInMainHand()))return;e.setCancelled(true);ItemStack filled=filled(mob);ItemStack hand=e.getPlayer().getInventory().getItemInMainHand();if(hand.getAmount()==1)e.getPlayer().getInventory().setItemInMainHand(filled);else{hand.setAmount(hand.getAmount()-1);e.getPlayer().getInventory().addItem(filled).values().forEach(i->e.getPlayer().getWorld().dropItemNaturally(e.getPlayer().getLocation(),i));}mob.remove();}
 @EventHandler(ignoreCancelled=true) public void release(PlayerInteractEvent e){if(e.getHand()!=EquipmentSlot.HAND||e.getAction()!=Action.RIGHT_CLICK_BLOCK||e.getClickedBlock()==null||!filled(e.getItem()))return;e.setCancelled(true);Properties p=read(e.getItem());if(p==null){e.getPlayer().sendMessage("§cДанные ведра повреждены.");return;}try{EntityType type=EntityType.valueOf(p.getProperty("type"));Location l=e.getClickedBlock().getRelative(e.getBlockFace()).getLocation().add(.5,0,.5);Entity entity=l.getWorld().spawnEntity(l,type);if(entity instanceof LivingEntity mob){restore(mob,p);consume(e.getPlayer(),e.getItem());}}catch(Exception ex){e.getPlayer().sendMessage("§cНе удалось выпустить моба.");}}
 public void registerRecipes(){NamespacedKey key=new NamespacedKey(plugin,"mob_bucket");plugin.getServer().removeRecipe(key);ShapedRecipe r=new ShapedRecipe(key,emptyItem());r.shape(" I ","IBI"," I ");r.setIngredient('I',Material.IRON_INGOT);r.setIngredient('B',Material.BUCKET);plugin.getServer().addRecipe(r);}
 private ItemStack emptyItem(){ItemStack i=new ItemStack(Material.BUCKET);ItemMeta m=i.getItemMeta();m.setDisplayName("§6Ведро для мобов");m.getPersistentDataContainer().set(bucketKey,PersistentDataType.BYTE,(byte)1);i.setItemMeta(m);return i;}
 private ItemStack filled(LivingEntity mob){ItemStack i=emptyItem();ItemMeta m=i.getItemMeta();m.setDisplayName("§6Ведро: §f"+mob.getType().name());m.getPersistentDataContainer().set(dataKey,PersistentDataType.STRING,encode(state(mob)));i.setItemMeta(m);return i;}
 private boolean empty(ItemStack i){return i!=null&&i.getType()==Material.BUCKET&&i.hasItemMeta()&&i.getItemMeta().getPersistentDataContainer().has(bucketKey,PersistentDataType.BYTE)&&!i.getItemMeta().getPersistentDataContainer().has(dataKey,PersistentDataType.STRING);}
 private boolean filled(ItemStack i){return i!=null&&i.hasItemMeta()&&i.getItemMeta().getPersistentDataContainer().has(bucketKey,PersistentDataType.BYTE)&&i.getItemMeta().getPersistentDataContainer().has(dataKey,PersistentDataType.STRING);}
 private Properties state(LivingEntity e){Properties p=new Properties();p.setProperty("type",e.getType().name());p.setProperty("health",Double.toString(e.getHealth()));p.setProperty("name",e.getCustomName()==null?"":e.getCustomName());p.setProperty("silent",Boolean.toString(e.isSilent()));p.setProperty("invulnerable",Boolean.toString(e.isInvulnerable()));p.setProperty("glowing",Boolean.toString(e.isGlowing()));p.setProperty("fire",Integer.toString(e.getFireTicks()));if(e instanceof Ageable a)p.setProperty("adult",Boolean.toString(a.isAdult()));if(e instanceof Tameable t){p.setProperty("tamed",Boolean.toString(t.isTamed()));if(t.getOwnerUniqueId()!=null)p.setProperty("owner",t.getOwnerUniqueId().toString());}if(e instanceof Sheep s){p.setProperty("color",s.getColor().name());p.setProperty("sheared",Boolean.toString(s.isSheared()));}if(e instanceof Horse h){p.setProperty("horseColor",h.getColor().name());p.setProperty("horseStyle",h.getStyle().name());}if(e instanceof Rabbit r)p.setProperty("rabbit",r.getRabbitType().name());for(NamespacedKey k:e.getPersistentDataContainer().getKeys()){if(!k.getNamespace().equals(plugin.getName().toLowerCase(Locale.ROOT)))continue;String v=e.getPersistentDataContainer().get(k,PersistentDataType.STRING);if(v!=null){p.setProperty("pdc."+k.getKey(),v);}}return p;}
 private void restore(LivingEntity e,Properties p){e.setCustomName(p.getProperty("name").isEmpty()?null:p.getProperty("name"));e.setSilent(Boolean.parseBoolean(p.getProperty("silent","false")));e.setInvulnerable(Boolean.parseBoolean(p.getProperty("invulnerable","false")));e.setGlowing(Boolean.parseBoolean(p.getProperty("glowing","false")));e.setFireTicks(num(p.getProperty("fire"),0));if(e instanceof Ageable a){if(Boolean.parseBoolean(p.getProperty("adult","true")))a.setAdult();else a.setBaby();}if(e instanceof Tameable t){t.setTamed(Boolean.parseBoolean(p.getProperty("tamed","false")));try{String o=p.getProperty("owner");if(o!=null)t.setOwner(plugin.getServer().getOfflinePlayer(UUID.fromString(o)));}catch(Exception ignored){}}if(e instanceof Sheep s){try{s.setColor(DyeColor.valueOf(p.getProperty("color",s.getColor().name())));}catch(Exception ignored){}s.setSheared(Boolean.parseBoolean(p.getProperty("sheared","false")));}if(e instanceof Horse h){try{h.setColor(Horse.Color.valueOf(p.getProperty("horseColor",h.getColor().name())));h.setStyle(Horse.Style.valueOf(p.getProperty("horseStyle",h.getStyle().name())));}catch(Exception ignored){}}if(e instanceof Rabbit r){try{r.setRabbitType(Rabbit.Type.valueOf(p.getProperty("rabbit",r.getRabbitType().name())));}catch(Exception ignored){}}for(String k:p.stringPropertyNames())if(k.startsWith("pdc."))e.getPersistentDataContainer().set(new NamespacedKey(plugin,k.substring(4)),PersistentDataType.STRING,p.getProperty(k));double h=number(p.getProperty("health"),e.getHealth());if(e.getAttribute(Attribute.MAX_HEALTH)!=null)h=Math.max(.1,Math.min(h,e.getAttribute(Attribute.MAX_HEALTH).getValue()));e.setHealth(h);}
 private void consume(Player p,ItemStack i){p.getInventory().setItemInMainHand(emptyItem());}
 private String encode(Properties p){try(ByteArrayOutputStream out=new ByteArrayOutputStream()){p.store(out,null);return Base64.getEncoder().encodeToString(out.toByteArray());}catch(IOException e){return "";}}
 private Properties read(ItemStack i){try{String s=i.getItemMeta().getPersistentDataContainer().get(dataKey,PersistentDataType.STRING);if(s==null)return null;Properties p=new Properties();p.load(new ByteArrayInputStream(Base64.getDecoder().decode(s)));return p;}catch(Exception e){return null;}}
 private int num(String s,int d){try{return Integer.parseInt(s);}catch(Exception e){return d;}} private double number(String s,double d){try{return Double.parseDouble(s);}catch(Exception e){return d;}}
}